python main.py \
--exp_name $exp_name$ \
--dataset_name mimic_cxr \
--label_path $path_to_label$  \
--max_seq_length 100 \
--threshold 10 \
--batch_size 64 \
--epochs 30 \
--lr_ve 5e-5 \
--lr_ed 1e-4 \
--save_dir results/mimic_cxr \
--ve_name densenet121 \
--ed_name r2gen \
--early_stop 10 \
--d_vf 768 \
--weight_decay 5e-5 \
--optim Adam \
--decay_epochs 50 \
--warmup_epochs 3 \
--warmup_lr 5e-6 \
--lr_scheduler step \
--decay_rate 0.8 \
--seed 456789 \
--randaug \
--addcls \
--cls_w 1 \
--evidence_chain \
--num_anatomy_queries 8 \
--num_disease_labels 14 \
--evidence_cov_w 0.5 \
--evidence_pos_tau 0.15
